-- Tabla centralizada de comandos administrativos por dialecto SQL.
-- La usan tanto el highlight (sql_admin_highlight.lua) como el
-- autocompletado (blink_sql_admin_source.lua), así nunca se desincronizan.
return {
    mysql = {
        "SHOW",
        "DESCRIBE",
        "DESC",
        "USE",
        "EXPLAIN",
        "HELP",
        "ANALYZE TABLE",
        "CHECK TABLE",
        "CHECKSUM TABLE",
        "OPTIMIZE TABLE",
        "REPAIR TABLE",
        "CREATE USER",
        "DROP USER",
        "ALTER USER",
        "RENAME USER",
        "CREATE ROLE",
        "DROP ROLE",
        "GRANT",
        "REVOKE",
        "SET PASSWORD",
        "SET ROLE",
        "SET DEFAULT ROLE",
        "FLUSH",
        "RESET",
        "KILL",
        "SHUTDOWN",
        "RESTART",
        "BINLOG",
        "CACHE INDEX",
        "LOAD INDEX INTO CACHE",
        "PURGE BINARY LOGS",
        "LOCK TABLES",
        "UNLOCK TABLES",
        "INSTALL PLUGIN",
        "UNINSTALL PLUGIN",
        "INSTALL COMPONENT",
        "UNINSTALL COMPONENT",
    },

    postgres = {
        "SHOW",
        "VACUUM",
        "ANALYZE",
        "EXPLAIN",
        "REINDEX",
        "CLUSTER",
        "CHECKPOINT",
        "LISTEN",
        "NOTIFY",
        "UNLISTEN",
        "SET",
        "RESET",
        "GRANT",
        "REVOKE",
        "CREATE ROLE",
        "ALTER ROLE",
        "DROP ROLE",
        "CREATE USER",
        "COPY",
        "DISCARD",
        "COMMENT ON",
        "LOCK",
        "DECLARE",
        "FETCH",
        "MOVE",
        "CLOSE",
        "PREPARE",
        "EXECUTE",
        "DEALLOCATE",
    },

    sqlite = {
        "PRAGMA",
        "VACUUM",
        "ANALYZE",
        "ATTACH DATABASE",
        "DETACH DATABASE",
        "REINDEX",
        "EXPLAIN",
        "EXPLAIN QUERY PLAN",
    },

    tsql = { -- MSSQL / SQL Server
        "EXEC",
        "EXECUTE",
        "USE",
        "GRANT",
        "REVOKE",
        "DENY",
        "BACKUP DATABASE",
        "RESTORE DATABASE",
        "DBCC",
        "SET",
        "PRINT",
        "RAISERROR",
        "THROW",
        "CREATE LOGIN",
        "ALTER LOGIN",
        "DROP LOGIN",
        "CREATE USER",
        "ALTER USER",
        "DROP USER",
        "SHUTDOWN",
        "KILL",
        "CHECKPOINT",
        "TRUNCATE TABLE",
    },

    -- H2/Vertica: cobertura best-effort, menos exhaustiva que las anteriores.
    h2 = {
        "SET",
        "SHUTDOWN",
        "SCRIPT",
        "RUNSCRIPT",
        "BACKUP",
        "ANALYZE",
        "EXPLAIN",
        "GRANT",
        "REVOKE",
        "CREATE USER",
        "ALTER USER",
        "DROP USER",
        "CREATE ROLE",
        "DROP ROLE",
        "CHECKPOINT",
    },

    vertica = {
        "EXPLAIN",
        "PROFILE",
        "COPY",
        "EXPORT TO",
        "GRANT",
        "REVOKE",
        "CREATE PROJECTION",
        "DROP PROJECTION",
        "ALTER RESOURCE POOL",
        "SET SESSION",
        "SHOW",
        "CONNECT",
        "DISCONNECT",
    },
}
